# Generated by Django 2.1.1 on 2019-04-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
