# Generated by Django 2.1.1 on 2019-04-07 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fileuploads', '0002_fileupload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='upload_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
