# Generated by Django 2.1.1 on 2019-04-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileuploads', '0003_fileupload_upload_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='body',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='file',
            field=models.FileField(default='default.png', upload_to='uploads/'),
        ),
    ]
